### ISSUE TITLE
google_tag_params dataLayer variable remains undefined

### ISSUE THREAD

**Issue by henkisdabro** [duracelltomi/gtm4wp#100]
I am not sure which details are supposed to be populated in the google_tag_params dataLayer key, but it stays undefined on all pages. Can you clarify whether this is a bug or if something in the settings needs adjustment? See screenshot below. 

![image](https://user-images.githubusercontent.com/477513/48192594-2d98a700-e383-11e8-9c38-fd87ee897084.png)

_PS. Feel free to also rename "AdWords" to "Google Ads" when the time is right as Google has renamed their product suite._

**Comment by Brendonwbrown** [comment]
google_tag_params is the specific variable for Adwords parameters. 
Do you have that enabled in the plugin?

![capture](https://user-images.githubusercontent.com/2648103/48205979-23928c00-e322-11e8-9198-bad3181a8b2a.JPG)

**Comment by duracelltomi** [comment]
This is a known bug that will be fixed in the next plugin version.
The problem here is that some cache plugin with code minimize feature also remove markup from the JavaScript code and this makes the browser to believe that the content of the google_tag_params variable is undefined.

In the meantime, you can add the required variable manually one by one into your GAds remarketing tag.

**Comment by koconder** [comment]
@duracelltomi in terms of cache busting, we could look at 3rd party linkage hooks with some of the cache plugins, will require more testing but could be an option: 

http://hookr.io/plugins/w3-total-cache/0.9.5.1/hooks/#index=a
https://docs.wp-rocket.me/category/713-filters/2?sort=name

**Comment by thorenw** [comment]
@duracelltomi Do you have any updates on when the next plugin version will be available?  It's very convenient when the 'google_tag_params' are working and sending over the data correctly.

Thanks for an awesome plugin!

**Comment by duracelltomi** [comment]
@thorenw  I am already testing the next bugfix version on various sites :-)

https://github.com/duracelltomi/gtm4wp/releases/tag/1.9.1beta

**Comment by duracelltomi** [comment]
@koconder yes, something needs to be done with cache plugins since I get wrong IP addresses and geo data in pages if any cache plugin is active

**Comment by michaeleugene89** [comment]
I also notice enabling the Remarketing variable it causes the checkout behavior analysis in GA is not functioning or no data.  Or did i miss something?

**Comment by duracelltomi** [comment]
I (we?) will need to check all popular cache plugins one by one since as far as I can see different projects handle partly caching in different ways. For example I was playing with WP Rocket and as far as I've seen it is not possible to tell the plugin not to cache the part of the head element where the data layer content is generated.

It could be one option to lazy load the data layer content with ajax but this would increase the number of network requests and I can see the flooding of my inbox from users who run GMetrix reports pointing to the extra line :-)

**Comment by duracelltomi** [comment]
Closing this issue as the main issue reported has been fixed (https://github.com/duracelltomi/gtm4wp/commit/47958f4babc513e6e814d04c826ab61fcf86ba13), discussion about cache plugins has been moved to a new thread.
