### ISSUE TITLE
Abillity to Support Adobe Launch and 3rd Party DataLayers

### ISSUE THREAD

**Issue by koconder** [duracelltomi/gtm4wp#127]
Refactoring to support 3rd party dataLayer applications such as Adobe Launch, thus allowing this plugin to become a DataLayer application plugin supporting Google Tag Manager, Google Optimize, AMP, Facebook AI, Adobe DTM/Adobe Launch.

Launch documentation: https://helpx.adobe.com/analytics/kt/using/data-layer-set-variables-launch-technical-video-implement.html

**Comment by duracelltomi** [comment]
It would be great to move into this direction but as far as I have seen the data layer structure of other TMS is very different from the one that GTM can use of. Since there are still many items on the TODO list, I am not sure when this refactoring could take place

**Comment by duracelltomi** [comment]
@koconder I reviewed the video of Adobe and as far as I can see they do not really have any specific data layer specification, in their video they are using the [W3C digital data layer](https://www.w3.org/community/custexpdata/2013/12/16/final-report-customer-experience-digital-data-layer-v1-0-ready/) spec which was never really finalized and as far is I can see it is quite an abandoned project within W3C

With that, anyone using GTM4WP with the code placement option set to OFF and adding the necessary Adobe tracking code could use the data layer provided by GTM4WP already.

Tealium has its own implementation of the data layer:
https://community.tealiumiq.com/t5/iQ-Tag-Management/Data-Layer-Variables/ta-p/9427
https://docs.tealium.com/platforms/javascript/about-utag-data/

But it does not seem to support nested values. They even provide a data layer converter tool to make sure that other structures (like the W3C proposal) can also work with their TMS as well:
https://community.tealiumiq.com/t5/iQ-Tag-Management/Data-Layer-Converter/ta-p/17581

With that, again, using GTM4WP using the OFF placement option, adding the utag code manually and using this Data Layer Converter extension one could use this plugin as well.

What needs to be done however is to reorganize data layer variables. Some variable groups are old fashioned singleVariableNames, others use fancy.new.nested.values . I would move this to the more structured data layer format by changing the existing variable groups one by one, version by version so that everyone has time to adapt. And of course new variables will be added with this format as well.
