### ISSUE TITLE
Problems with display of background images

### ISSUE THREAD

**Issue by ferremek** [duracelltomi/gtm4wp#139]
When I use this plugin on a website of a client all of a sudden the background images don't show up anymore or are way too high when viewed in Safari. When I disable the plugin everything goes back to normal.

Any ideas how to fix this? See http://kruit.staging.jvdmedia.nl/advies/ for the website in a staging environment.

I use the following CSS to style the images and add the background-image with an URL inline:
```
.background-image {
    display: block;
    width: 100%;
    height: 100%;
    background-size: cover;
    background-position: center;
}
```

**Comment by duracelltomi** [comment]
If you replace the container ID in GTM4WP plugin settings to something dummy (like GTM-XXXXXX), while you keep the plugin active, does this issue still persist?

**Comment by ferremek** [comment]
Thanks for your response! Do you mean the "Google Tag Manager ID" on the first tab?

**Comment by duracelltomi** [comment]
Yes

Since GTM4WP does not include any code that could be related to your issue, my assumption is that your GTM container itself might include a tag that causes this behavior. Since when you disable the plugin, you also remove the GTM container itself, it can be that the issue is inside your container and not in the plugin.

If you change the container ID in plugin settings to a fake ID, the plugin itself can be kept active and we can see whether my hypothesis is true.

**Comment by ferremek** [comment]
Nope, that doesn't change anything. Only if I put the placement on "Codeless injection" it fixes the issue. I will see if this option will work and won't break anything. Still very strange behaviour though! Do you have any other idea where I can look?

**Comment by ferremek** [comment]
Seems to be solved! I am using the Timber framework and I added the function through functions.php first and I moved it straight into the template now. Everything seems to work perfectly! Thanks again for your response!
