### ISSUE TITLE
Code Placement = OFF stops GTM being added

### ISSUE THREAD

**Issue by leesherwood** [duracelltomi/gtm4wp#159]
When I set **Container Code Placement = Off (only add data layer to the page source)** , the plugin no longer add's the GTM script to the `<head></head>` section. Essentially this is the same as deactivating the plugin?

However the description is as follows:

> Code placement decides where to put the second, so called noscript part of the GTM container code.
This code is usually only executed if your visitor has for some reason disabled JavaScript.
The main GTM container code will be placed into the <head> section of your webpages anyway (where it belongs to).

Which indicates this is not what is supposed to happen, and setting this to OFF should simply stop the `<noscript>` being added to the `<body>` section.

**Comment by duracelltomi** [comment]
"Off" code placement is meant to deactivate the container code itself while maintaining the data layer in the site.

This placement option is for some edge cases where more advanced users would like to tweak with the container code. I have to admit that the description is confusing since this is the only option that has an effect on the head code as well.

Since WP 5.2 introduced a way to add the noscript tag after the opening body tag, I think it would be better to replace this "Placement option" section with two new sections:

#1 Container code on/off - handles both the head and body script
#2 Compatibility mode - here we could show 3 options: "off", "manual" and "footer". "off" would turn off the compatibility mode itself, "manual" and "footer" would work as the currently available placement options.

What do you think?

**Comment by leesherwood** [comment]
Sounds like a good idea to me :)
