### ISSUE TITLE
Need to add checkout step event for woocommerce

### ISSUE THREAD

**Issue by outoftheboxsol** [duracelltomi/gtm4wp#170]
Hi there,
I've noted a bug in the woocomerce integration side of the plugin that's an easy fix.

You're not feeding the event name into the checkout page load datalayer.

See line 600 of your file duracelltomi-google-tag-manager/integration/woocommerce.php

If should include $dataLayer['event']     = 'gtm4wp.checkoutStepEEC';

Or else you're adding the data layer value, but firing no event.

Thanks for your work on this plugin :)

**Comment by kpapamanos** [comment]
Yes! I was also trying to figure this out. All the checkout steps were firing except the first one.
Now it is working as expected. Thanks! 😊

**Comment by duracelltomi** [comment]
Hi Everyone,

Sorry for this very long reply time.
This is currently the expected behavior if you setup enhanced ecommerce tracking as described in the official doc:
https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking

In that case, the first checkout step will be traced with the checkout pageview itself.
