### ISSUE TITLE
Google Analytics 4 ecommerce dataLayer bugs/comments

### ISSUE THREAD

**Issue by ju1** [duracelltomi/gtm4wp#180]
**view_item_list**
- missing "item_list_name" parameter next to each product (should contain the same value as "list" from EE)
- Missing "index" parameter next to each product (should contain the same value as "position" from EE)

*view_cart*
- I can't see this event in the dataLayer when I go here https://woo.gtm4wp.dev/cart

**begin_checkout**
- It would be easier if we got a dataLayer.push with the event name _begin_checkout_. Right now, the push happens before the gtm.js event and that push does not have the "event" key, so it will be a bit more difficult to trigger a tag for beginners. Although, I see where you are going with the "ecommerce_event" key, having the proper "event" key in the dataLayer.push would be good

**add_shipping_info** 
When I selected "Ship to a different address" and started entering the address, the EEC dataLayer.push (for checkout step2 ) fired, but there was no GA4 data. But if I disable the "ship to different address checkbox" and then make a purchase, then I get the purchase data layer + checkout dataLayer.push, and that one contains the GA4 data properly

**Comment by ju1** [comment]
My bad about view_cart. I missed that.

>begin_checkout
>How about having a GTM event name but in the initial dL push just like with the order received event?
You mean like a separate dataLayer.push? 

>add_shipping_info is about entering any kind of shipping data (including name or method) or it is only the method in your opinion?
In my opinion, it should be when the method is selected (because shipping_tier is a required field for add_shipping_info.


One more thought - I'd say that it would be better to have a separate checkbox in the plugin to enable GA4 ecommerce data layer. Right now, most of the GA4 ecomm data is available with the dataLayer.push that is using "EEC" in the event name. And the name of EEC is going to be less and less relevant in the future. Imagine someone after 2 years enabling the ecomm data in your plugin and they still see something called EEC. Some people might not even know what it is :) Maybe it's time to have a separate checkbox and separate dataLayer.pushes for EEC and GA4 (where the 'event' key is included). The final decision should be made now because in the future changing event names will be more painful because there will be many GA4 setups that will be using "EEC" events in their GTM triggers.

**Comment by duracelltomi** [comment]
begin_checkout: no, to keep backward compatibility, data for the first checkout step has to be kept in the initial dL.push (before the container code). But I can add an "event" key so that one can create a separate trigger and tag that reads GA4 data. This is the same logic that is working on the order received page.

add_shipping_info: this is how currently the plugin is adding ecommerce data: if you select a shipping method OR if you do not change the default selection (either because you accept the default selection or because this section is hidden due to having only one option)

Separate checkbox and events: I am open for this but this will also increase the complexity of plugin options. On the mid-term, I plan to remove "standard" ecommerce tracking as this is now more and more obsolete but I am also a bit afraid that still many setups rely on that. So first, I will mark standard ecommerce as deprecated and sometime later this year I will actually remove this to give time for plugin users to update their measurement setups.

Still, if I move to have GA4 data in separate dL.pushes, I think the newly introduced "ecommerce_event" key should be kept and actual GTM event names could be more closer to the naming convention I am using with other events.

I am not sure I can imagine what will happen 2 years from now :-) Perhaps we will beta test GA5 LOL :-D

**Comment by duracelltomi** [comment]
I started to change events but there is one obstacle: for events happening during page load (view_item, begin_checkout, purchase) codes are quite bound to the head section currently. It would be a bigger task to move them to somewhere else after the GTM container load.

Already separate events (add to cart, checkout step, product list click) are easy to move to a second dL push with GA4 data only.

What do you think of this?

**Comment by ju1** [comment]
> Separate checkbox and events: I am open for this but this will also increase the complexity of plugin options. On the mid-term, I plan to remove "standard" ecommerce tracking as this is now more and more obsolete but I am also a bit afraid that still many setups rely on that. So first, I will mark standard ecommerce as deprecated and sometime later this year I will actually remove this to give time for plugin users to update their measurement setups.
Good call

> I am not sure I can imagine what will happen 2 years from now :-) Perhaps we will beta test GA5 LOL :-D
I hope that will not happen.

>I started to change events but there is one obstacle: for events happening during page load (view_item, begin_checkout, purchase) codes are quite bound to the head section currently. It would be a bigger task to move them to somewhere else after the GTM container load. 
Can't they have the event key even if they are in the head? Sorry if the question is stupid, I am not much familiar with the "under the hood" stuff of WP.

Quick question: is your current plan to have the separate checkbox for GA4 Ecommerce in the plugin's settings?

**Comment by duracelltomi** [comment]
Here is where I am now:
* I decided to decouple GA4 version of ecommerce events from existing EEC events
* I do not plan to include a separate checkbox for GA4 version events
* I will fire two separete dL.push() on each event, the first will be the GA3 "style", the second will be the GA4 "style"
* GA4 version will use the event names of the official Google docs (thus no ecommerce_event variable anymore)
    - this will make the GTM implementation more portable (either coming from another plugin or going to another solution or even replacing WooCommere with Magento)
    - it will also enable GTM variable templates, like the FB pixel of Simo to use the event key to decide what FB event needs to be fired regardless of the used plugin on the site
* ecommerce data that is present in the head (product detail, checkout first step and purchase) will fire a separate dL.push() in the GA4 version as well to use this single approach: you do not need to read anything during page load, you only need to catch certain data layer events and that's it ==> this will give everyone a much simpler GTM setup

https://woo.gtm4wp.dev/ already uses those changes, only the head codes needs to be adapted but I will do this tomorrow and release the first beta
