### ISSUE TITLE
Multiple dataLayer pushes for select_item event when GA4 config tag is present

### ISSUE THREAD

**Issue by prabapro** [duracelltomi/gtm4wp#186]
Hi @duracelltomi ,

I have a very strange issue where there are multiple dataLayer pushes for ```select_item``` event  **when a GA4 config tag is present**. Please refer to the below screenshots;

**Multiple pushes:**

![gtm4wp-with-ga4-config-tag](https://user-images.githubusercontent.com/32594937/116234758-a02bb600-a77a-11eb-854c-6d03ce936db9.png)

**Single push - when GA4 config tag is not present in the container or paused:**

![gtm4wp-with-ga4-config-tag-paused](https://user-images.githubusercontent.com/32594937/116234882-c9e4dd00-a77a-11eb-944a-cda2a74f3afb.png)

Few things I tested;

- Tested with an empty container - **no issue**
- Tested with some GA4 ecommerce event tags - issue is there
- Paused the GA4 config tag & kept the tags as is - **no issue**
- Changed the measurement ID - issue is there
- Disabled enhanced measurement - issue is there

Thanks,
Praba.

**Comment by duracelltomi** [comment]
Hi Praba,

Thanks for the details, I checked this and it seems that this is because of an undocumented (?) behavior of GTM' eventCallback() function.

Generally select_item event is pushed after the original gtm4wp.productClickEEC event is fired and handled within GTM. This is done in that way so that the redirect to the product detail page will be only done after both events have been dispatched. Until now I haven't seen any sample code that adds an argument to the eventCallback function but based on my testing today there seems to be one argument: it includes either the GA4 measurement ID or the GTM contanier ID. I do not know why this is called twice, I will do some more research and add a fix once I see a permanent solution.

**Comment by prabapro** [comment]
Hi Thomas,

Thank you so much for checking this :) Much appreciated.

Thanks,
Praba.
