### ISSUE TITLE
Possible incompatibility with WooCommerce Distance Rate Shipping - reload on checkout

### ISSUE THREAD

**Issue by lupetalo** [duracelltomi/gtm4wp#195]
Hello.

A client has a shop with [WooCommerce Distance Rate Shipping](https://woocommerce.com/products/woocommerce-distance-rate-shipping/) and when that plugin is active together with this one checkout page reloads after the client-side validation on the frontend. We got to this by updating everything and withstanding the painful process of turning on/off all plugins one by one in combination with WooCommerce Distance Rate Shipping + Woocommerce. 
Further examination showed that the issue is happening only when WooCommerce Distance Rate Shipping needs to fetch the data from the remote API (user enters enough information)
Everything is updated to the latest version...
A support ticket is opened with Automattic support a few days ago, but no reply... Is there something specific with this plugin that may cause a reload on the checkout page? I am emphasizing that the issue is happening only when those two plugins are active...

Thanks!

**Comment by duracelltomi** [comment]
Hi,

Before going too deep: could you test if the issue is present if GTM4WP is active but you replace the GTM container ID in plugin settings with this: GTM-XXXXX?

**Comment by lupetalo** [comment]
@duracelltomi Thanks for the reply :) College already tried that, unfortunately, the issue is still there. it is also possible to create access credential for you if needed :)

**Comment by duracelltomi** [comment]
Thanks but currently I do not see any reason to grant me admin access.
Can you post the URL of the site? Perhaps a test site where you can keep GTM4WP active without affecting the UX for real users?

**Comment by lupetalo** [comment]
Thank you soo much for taking the time to look at this! I hope somebody else will benefit from this as well :)

Here is a video of the production website: https://www.screencast.com/t/LroWQrrGbk7 Sorry for the length, I forgot that I have to use WPE SSO to log in :(  The first part is with the plugin disabled, and the second one with the plugin enabled. 

Here is a dev copy that you can test: https://copyliveprep.wpengine.com/ (order  more than 80€)

On Checkout try filling in all the correct details and for example not tick the 'terms and conditions all the way down. The page will reload :(

**Comment by lupetalo** [comment]
@duracelltomi Figured out the issue. This 'fake' trigger is causing reload. It is the JS file for enhanced tracking. It does not create issues with the flow. I recommend adding this as a setting in a future version.

**Comment by jmerilainen** [comment]
I also have issue with the shipping method's change event triggering when submitting the checkout form. I have one payment gateway plugin that requires to fill inputs in the payment section. The change event that @lupetalo described above wipes those input fields data (because it fetches fresh payment view with empty fields via ajax) before sending the checkout data and therefore causes validation error.

**Comment by jmerilainen** [comment]
It's true that the issue might be caused by the payment plugin or even combination with the shipping plugin.
I think the  `input[name=payment_method]` change will trigger WooCommerce's `$( document.body ).on( 'update_checkout', this.update_checkout )` event and the payment plugin (or/and shipping plugin) will listen that `update_checkout` and updates the view.

But yeah definitely the shipping method step should be pushed to the report somehow. 

Maybe instead of triggering the `change` event for `input[name^=shipping_method]` field could it just do the logic that is inside of `jQuery( document ).on( 'change', 'input[name^=shipping_method]', ...` binding [1]? So something like
```js
jQuery( 'form[name=checkout]' ).on( 'submit', function() { // [2]
  ...
    if ( selected_shipping_method.length > 0 ) {
          // selected_shipping_method.trigger( 'change' ); 
    	  reportShippingMethod(); // [1]
     }
  ...
}
```
Code references from master:
[1] https://github.com/duracelltomi/gtm4wp/blob/master/js/gtm4wp-woocommerce-enhanced.js#L765-L809
[2] https://github.com/duracelltomi/gtm4wp/blob/master/js/gtm4wp-woocommerce-enhanced.js#L869

**Comment by duracelltomi** [comment]
Sorry for this very long reply time.
I prepared a change where instead of triggering browser events, I will simply run the necessary functions as suggested by @jmerilainen 

https://github.com/duracelltomi/gtm4wp/commit/edaa50f1a7a060a8e7febc33a082968a0d64c65a
