### ISSUE TITLE
Remove extra id attribute, price must be in numerical format

### ISSUE THREAD

**Issue by arm923i** [duracelltomi/gtm4wp#232]
Tell me, how can I remove the extra “id” attribute with the data level, I only need the “item _id” attribute.
In the js code itself, I do not observe this attribute, is it probably added at some other stage of sending?
https://ibb.co/NWY7QKs
Also, the price must be in numerical format. Added the parseFloat function, but it does not give a result, it just goes like text.
https://ibb.co/1zN9GR2
Thanks in advance

**Comment by duracelltomi** [comment]
"id" is required by the Google Ads dynamic remarketing tagging.
You can use the gtm4wp_eec_product_array hook to remove this attribute:
https://gtm4wp.com/gtm4wp-for-developers/actions-and-filters-in-gtm4wp-for-developers

The price attribute is processed well even if it is converted to a string, did you had broken data collection and reporting because of that?

**Comment by arm923i** [comment]
Already figured it out, thanks.
This is an SEO audit requirement.
