### ISSUE TITLE
[Feature request] Matomo datalayer

### ISSUE THREAD

**Issue by StSaens** [duracelltomi/gtm4wp#251]
Hi, 
I've been using GTM4WP for several years now and am very happy with it.
Considering the movements of the EU with regards to GDPR and Google I'm working on moving my Analytics from Google to (self hosted) Matomo (https://matomo.org/) It also features a Tag Manager just like GTM.

Would it be possible to extend the GTM4WP-plugin with the Matomo datalayer? As far as I can see pretty much everything is identical to the Google way.

**Comment by duracelltomi** [comment]
Hi,

You can disable GTM container code output in GTM4WP options as well as rename the datalayer variable on the Advanced tab. My guess is that this would solve your request. Of course you will need to manually add the container code of Matomo TM.

Note: are you sure abandoning GA also means you need to abandon GTM itself? GTM does not store any data, I am not sure why you need to switch to Matomo TM instead of keep using GTM and implementing Matomo Analytics within?

**Comment by StSaens** [comment]
Hi. This indeed answers my question. Thanks!

note: You are right about that.
