### ISSUE TITLE
Blocking GTM causes WooCommerce to break

### ISSUE THREAD

**Issue by DavidKox** [duracelltomi/gtm4wp#27]
We have been pointed out that some of our customers were having issues with our shop. They weren't able to open products from the category pages.
When investigating it turns out that they were using an AdBlocker (AdGuard - Chrome - MacOS) and had set several filters to also block GTM.
With the Enhanced E-Commerce Option enabled the productClick event causes a major failure:

The preventDefault() disables the normal redirect and with GTM blocked by the user, the manual redirect that is implemented in the eventCallback is never triggered.

https://github.com/duracelltomi/gtm4wp/blob/master/integration/woocommerce.php#L721

Why do we use a manual redirect at all? What's the idea behind the preventDefault() here and why do we differentiate between a normal click and one with ctrl-key pressed? In my tests the Event is fired in any case also with the preventDefault and eventCallback removed. Am I missing something?

In any case this implementation should be addressed. We need a fallback if GTM is blocked.

**Comment by duracelltomi** [comment]
Hi David,

Thanks for sharing your findings!
There is a check on line 691 that was added to detect whether an adblocker is active that also blocks GTM:
https://github.com/duracelltomi/gtm4wp/blob/master/integration/woocommerce.php#L691

If I correctly understand you, this means that using this ad blocker the google_tag_manager global variable is still set?

About the preventDefault() and the callback: without this, the product click would immediately tell the browser to follow the link in the <a> element. Although GTM would start to fire corresponding triggers, execution of those code could be shut down since the browser replaces the current page with the new one.

Using this behavior, we allow GTM to fire all tags that is bound to the GTM event (gtm4wp.productClickEEC) and we instruct the browser to follow the link just after tags has been fired OR 2000ms has been passed as there is a timeout value in my code as well.
Unfortunately if GTM is blocked, this timeout value does not take into account as well but eventually the check at line 691 should prevent the whole product click event handler to execute.

I hope that helps to clarify the reasons and I hope we can find an even better solution to detect this ad blocker as well.

**Comment by DavidKox** [comment]
Update fixed it for me - We were still running on v1.5 without the block-controller.
