### ISSUE TITLE
Include new_customer in GA4 purchase too

### ISSUE THREAD

**Issue by luukfiets** [duracelltomi/gtm4wp#306]
Hi @duracelltomi,

We noticed that the legacy gtm4wp.orderCompletedEEC includes the new_customer attribute, but the GA4 datalayer equivalent does not. I think this is because the new_customer attribute is not included in the logic that transforms the GA3 style datalayer to the GA4 style datalayer.

![image](https://github.com/duracelltomi/gtm4wp/assets/25853477/c93e07e3-fe5b-4cb0-a0a2-b3a3b1990fe4)

If you could point me to the right lines in the code, I can maybe have a look at it and try to send in a pull request that fixes this missing data in the GA4 purchase event.

Best,
Luuk

**Comment by duracelltomi** [comment]
Hi,

The WooCommerce integration undergoes a big overhaul, legacy GA3 related events are removed, lots of code optimization happens.

I am already working on this on a local copy, I would say ~70% of WC related code is changing which also shrinks the file sizes.

Since it is not ready yet to be tested, I am not sure it is time to push changed into the repository. I do not recommend sending any PR since it will be mostly incompatible with the changes in the core.

However the mentioned part has already been restructured and the separate purchase event will include the new_customer variable as well. I am currently working on the JavaScript codes.

Since this is quite a big change, I would like to give everyone time to test, I would say this won't be released 'til end of January. If you need this immediately, I could give you an idea where to patch your instance.

**Comment by luukfiets** [comment]
That makes absolute sense. I will use the current setup and revisit it early next year.
