### ISSUE TITLE
Cloudflare Support

### ISSUE THREAD

**Issue by koconder** [duracelltomi/gtm4wp#75]
Extending feature request from #60 to detect `HTTP_CF_IPCOUNTRY` header in `$_SERVER['HTTP_CF_IPCOUNTRY'];`

This will output 2 letter ISO code for sites served via cloudflare, or XX for undefined or T1 for Tor network. May need testing with common caching plugins to ensure the HTTP headers are not cached. Might not be a straightforward setup.

**Comment by ahmed-sigmalux** [comment]
Seconding this request. Including the CF-IPCountry header result in the data layer would allow website owners to customize tag output per country, which could be helpful for GDPR or other legal requirements.

**Comment by duracelltomi** [comment]
There is a geo option in the plugin that can output country into the data layer:
https://github.com/duracelltomi/gtm4wp/blob/master/public/frontend.php#L398

I guess this is not yet compatible with Cloudflare as it uses freegeoip.net with the REMOTE_ADDR server variable:
https://freegeoip.net/json/'.$_SERVER['REMOTE_ADDR']

I would say it would be more smoother to improve that part of the plugin so that the same feature can be used for Cloudflare and non-Cloudflare users

**Comment by ahmed-sigmalux** [comment]
Cloudflare only provides the 2-letter ISO country code:

https://support.cloudflare.com/hc/en-us/articles/200168236-What-does-Cloudflare-IP-Geolocation-do-
